### ISSUE TITLE
Failed to load credentials from IMDS., com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper: Failed to connect to service endpoint

### ISSUE THREAD

**Issue by Akshaya-T** [aws/aws-msk-iam-auth#195]
**Overview**

- I am experimenting with Kafka UI. 
- I am trying to connect to a AWS MSK cluster in Kafka UI from a self managed kops cluster. 
- I can able to access the kafka clusters from the pod using awscli as the pod is annotated with kube2iam role. 
- I am facing the following error from kafka-ui.

**Configuration**
------------------------------
~/.aws/config
[default]
    role_arn = arn:aws:iam::<account-id>:role/kafka-ui-kops-kube2iam-role
    region = us-east-2
    credential_source = Ec2InstanceMetadata
    role_session_name = kafka-ui
---------------
Helm values file

env:
  - name: KAFKA_CLUSTERS_0_NAME
    value: test 
  - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
    value: b-1.test.qfyzys.c3.kafka.us-east-2.amazonaws.com:9098
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
    value: SASL_SSL 
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
    value: AWS_MSK_IAM 
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_CLIENT_CALLBACK_HANDLER_CLASS
    value: software.amazon.msk.auth.iam.IAMClientCallbackHandler 
  - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
    value: software.amazon.msk.auth.iam.IAMLoginModule required awsProfileName="default"; 

------------------------------

**Error**

12-30 16:17:26,130 WARN  [kafka-admin-client-thread | kafbat-ui-admin-1735575433-519] s.a.m.a.i.i.MSKCredentialProvider: Exception loading credentials. Retry Attempts: 3
com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [software.amazon.msk.auth.iam.internals.EnhancedProfileCredentialsProvider@66c60036: Failed to load credentials from IMDS., com.amazonaws.auth.AWSCredentialsProviderChain@41a51f30: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, software.amazon.msk.auth.iam.internals.EnhancedProfileCredentialsProvider@5ee7edcb: Failed to load credentials from IMDS., com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@ea30419: Failed to connect to service endpoint: ]]
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.loadCredentialsWithRetry(MSKCredentialProvider.java:154)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.getCredentials(MSKCredentialProvider.java:141)
	at software.amazon.msk.auth.iam.IAMClientCallbackHandler.handleCallback(IAMClientCallbackHandler.java:100)
	at software.amazon.msk.auth.iam.IAMClientCallbackHandler.handle(IAMClientCallbackHandler.java:77)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:139)
	at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:96)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:534)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.base/javax.security.auth.Subject.doAs(Subject.java:439)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:534)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:433)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:332)
	at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:273)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:181)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:571)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1413)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1344)
	at java.base/java.lang.Thread.run(Thread.java:840)
2024-1

**Comment by syydas** [comment]
Hi team, we also meet `SdkClientException` like above when we upgrade to `2.2.0`

Error details:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Either the environment variable AWS_WEB_IDENTITY_TOKEN_FILE or the javaproperty aws.webIdentityTokenFile must be set., ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])): Profile file contained no credentials for profile 'default': ProfileFile(sections=[]), ContainerCredentialsProvider(): Interrupted waiting to refresh a cached value., InstanceProfileCredentialsProvider(): Interrupted waiting to refresh a cached value.]
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
at software.amazon.awssdk.auth.credentials.AwsCredentialsProviderChain.resolveCredentials(AwsCredentialsProviderChain.java:130)
at software.amazon.awssdk.auth.credentials.internal.LazyAwsCredentialsProvider.resolveCredentials(LazyAwsCredentialsProvider.java:45)
at software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider.resolveCredentials(DefaultCredentialsProvider.java:129)
at software.amazon.awssdk.auth.credentials.AwsCredentialsProvider.resolveIdentity(AwsCredentialsProvider.java:54)
at software.amazon.awssdk.services.kms.auth.scheme.internal.KmsAuthSchemeInterceptor.lambda$trySelectAuthScheme$4(KmsAuthSchemeInterceptor.java:132)
at software.amazon.awssdk.core.internal.util.MetricUtils.reportDuration(MetricUtils.java:77)
at software.amazon.awssdk.services.kms.auth.scheme.internal.KmsAuthSchemeInterceptor.trySelectAuthScheme(KmsAuthSchemeInterceptor.java:132)
at software.amazon.awssdk.services.kms.auth.scheme.internal.KmsAuthSchemeInterceptor.selectAuthScheme(KmsAuthSchemeInterceptor.java:81)
at software.amazon.awssdk.services.kms.auth.scheme.internal.KmsAuthSchemeInterceptor.beforeExecution(KmsAuthSchemeInterceptor.java:61)
at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.lambda$beforeExecution$1(ExecutionInterceptorChain.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.beforeExecution(ExecutionInterceptorChain.java:59)
at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.runInitialInterceptors(AwsExecutionContextBuilder.java:248)
at software.amazon.awssdk.awscore.internal.AwsExecutionContextBuilder.invokeInterceptorsAndCreateExecutionContext(AwsExecutionContextBuilder.java:138)
at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.invokeInterceptorsAndCreateExecutionContext(AwsSyncClientHandler.java:67)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:76)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:182)
at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:74)
at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:53)
at software.amazon.awssdk.services.kms.DefaultKmsClient.decrypt(DefaultKmsClient.java:1958)
at com.reagroup.personalisation.user.profile.dispatcher.common.KeyDecryptor$.$anonfun$apply$1(KeyDecryptor.scala:42)
at scala.Option.map(Option.scala:230)
at com.reagroup.personalisation.user.profile.dispatcher.common.KeyDecryptor.$anonfun$decrypt$1(KeyDecryptor.scala:25)
at scala.util.Try$.apply(Try.scala:213)
at com.reagroup.personalisation.user.profile.dispatcher.common.KeyDecryptor.decrypt(KeyDecryptor.scala:26)
at com.reagroup.personalisation.user.profile.dispatcher.common.KeyDecryptor.$anonfun$decryptEnvMap$1(KeyDecryptor.scala:32)
at cats.data.Chain$.$anonfun$traverseViaChain$3(Chain.scala:1018)
at cats.Eval$.loop$1(Eval.scala:340)
at cats.Eval$.cats$Eval$$evaluate(Eval.scala:386)
at cats.Eval$FlatMap.value(Eval.scala:307)
at cats.data.Chain$.traverseViaChain(Chain.scala:1040)
at cats.instances.ListInstances$$anon$1.traverse(list.scala:131)
at cats.instances.ListInstances$$anon$1.traverse(list.scala:38)
at cats.Traverse$Ops.traverse(Traverse.scala:243)
at cats.Traverse$Ops.traverse$(Traverse.scala:242)
at cats.Traverse$ToTraverseOps$$anon$3.traverse(Traverse.scala:280)
at com.reagroup.personalisation.user.profile.dispatcher.common.KeyDecryptor.decryptEnvMap(KeyDecryptor.scala:30)
at com.reagroup.personalisation.user.profile.dispatcher.common.config.EnvironmentVariable$.$anonfun$envMap$2(EnvironmentVariable.scala:33)
at com.reagroup.personalisation.user.profile.dispatcher.common.config.EnvironmentVariable.envMap(EnvironmentVariable.scala:21)
at com.reagroup.personalisation.user.profile.dispatcher.common.config.EnvironmentVariable$.envMap(EnvironmentVariable.scala:34)
at com.reagroup.personalisation.user.profile.dispatcher.common.config.SqsConfig$.config(SqsConfig.scala:17)
at com.reagroup.personalisation.user.profile.dispatcher.common.client.SQSErrorPublisher.<init>(SQSErrorPublisher.scala:13)
at com.reagroup.personalisation.user.profile.dispatcher.tealium.tealiumSink.TealiumSinkWriter.handleNonFatalError(TealiumSinkWriter.scala:112)
at com.reagroup.personalisation.user.profile.dispatcher.tealium.tealiumSink.TealiumSinkWriter.<init>(TealiumSinkWriter.scala:36)
at com.reagroup.personalisation.user.profile.dispatcher.tealium.tealiumSink.TealiumSink.createWriter(TealiumSink.scala:10)
at org.apache.flink.api.connector.sink2.Sink.createWriter(Sink.java:78)
at org.apache.flink.streaming.runtime.operators.sink.StatelessSinkWriterStateHandler.createWriter(StatelessSinkWriterStateHandler.java:39)
at org.apache.flink.streaming.runtime.operators.sink.SinkWriterOperator.initializeState(SinkWriterOperator.java:148)
at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:147)
at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:294)
at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.initializeStateAndOpenOperators(RegularOperatorChain.java:106)
at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreStateAndGates(StreamTask.java:858)
at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$restoreInternal$5(StreamTask.java:812)
at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.call(StreamTaskActionExecutor.java:55)
at org.apache.flink.streaming.runtime.tasks.StreamTask.restoreInternal(StreamTask.java:812)
at org.apache.flink.streaming.runtime.tasks.StreamTask.restore(StreamTask.java:771)
at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:972)
at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:941)
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:765)
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:577)
at java.base/java.lang.Thread.run(Thread.java:829)
```

```
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder.
at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$1(DefaultSdkHttpClientBuilder.java:49)
at java.base/java.util.Optional.orElseThrow(Optional.java:408)
at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:43)
at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$17(SdkDefaultClientBuilder.java:452)
at java.base/java.util.Optional.orElseGet(Optional.java:369)
at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:452)
at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$finalizeSyncConfiguration$5(SdkDefaultClientBuilder.java:311)
at software.amazon.awssdk.utils.AttributeMap$DerivedValue.primeCache(AttributeMap.java:604)
at software.amazon.awssdk.utils.AttributeMap$DerivedValue.get(AttributeMap.java:593)
at software.amazon.awssdk.utils.AttributeMap$Builder.resolveValue(AttributeMap.java:400)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at software.amazon.awssdk.utils.AttributeMap$Builder.build(AttributeMap.java:362)
at software.amazon.awssdk.core.client.config.SdkClientConfiguration$Builder.build(SdkClientConfiguration.java:224)
at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:313)
at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:203)
at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:36)
at software.amazon.awssdk.services.sts.DefaultStsClientBuilder.buildClient(DefaultStsClientBuilder.java:25)
at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:169)
at software.amazon.msk.auth.iam.internals.MSKCredentialProvider$ProviderBuilder.createSTSRoleCredentialProvider(MSKCredentialProvider.java:359)
at software.amazon.msk.auth.iam.internals.MSKCredentialProvider$ProviderBuilder.lambda$getStsRoleProvider$4(MSKCredentialProvider.java:346)
at java.base/java.util.Optional.map(Optional.java:265)
at software.amazon.msk.auth.iam.internals.MSKCredentialProvider$ProviderBuilder.getStsRoleProvider(MSKCredentialProvider.java:323)
at software.amazon.msk.auth.iam.internals.MSKCredentialProvider$ProviderBuilder.getProviders(MSKCredentialProvider.java:259)
at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:112)
at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:108)
at software.amazon.msk.auth.iam.IAMClientCallbackHandler.lambda$configure$1(IAMClientCallbackHandler.java:54)
at java.base/java.util.Optional.map(Optional.java:265)
at software.amazon.msk.auth.iam.IAMClientCallbackHandler.configure(IAMClientCallbackHandler.java:54)
at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:151)
... 20 more
```
Context:
- The version before 2.1.x can works well
- We used aws kda to run the app
- We used the below config for the connection 
    ```
    val region = DefaultAwsRegionProviderChain.builder().build().getRegion
        val properties = new Properties()
        if (config.securityProtocol == SecurityProtocol.SASL_SSL.toString) {
          val iamRoleConfig =
            s"""software.amazon.msk.auth.iam.IAMLoginModule required awsRoleArn="${config.hydroIamRole}" awsStsRegion="${region}";"""
        properties.put(SASL_JAAS_CONFIG, iamRoleConfig)
        properties.put(SASL_MECHANISM, "AWS_MSK_IAM")
        properties.put(SASL_CLIENT_CALLBACK_HANDLER_CLASS, "software.amazon.msk.auth.iam.IAMClientCallbackHandler")
      }
  ```
