### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.auth.DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by erichulburd** [aws/aws-msk-iam-auth#24]
I'm trying to deploy a Flink application on Kinesis using IAM authentication. The latest challenge is the following error when using this library:

Full trace:

```
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:820)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646)
	at org.apache.flink.streaming.connectors.kafka.internal.KafkaPartitionDiscoverer.initializeConnections(KafkaPartitionDiscoverer.java:58)
	at org.apache.flink.streaming.connectors.kafka.internals.AbstractPartitionDiscoverer.open(AbstractPartitionDiscoverer.java:94)
	at org.apache.flink.streaming.connectors.kafka.FlinkKafkaConsumerBase.open(FlinkKafkaConsumerBase.java:550)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$0(StreamTask.java:474)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:470)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:529)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:724)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:549)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.KafkaException: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.auth.DefaultAWSCredentialsProviderChain
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:741)
	... 15 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.auth.DefaultAWSCredentialsProviderChain
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.getListOfDelegates(MSKCredentialProvider.java:62)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:52)
	at software.amazon.msk.auth.iam.internals.MSKCredentialProvider.<init>(MSKCredentialProvider.java:47)
	at software.amazon.msk.auth.iam.IAMClientCallbackHandler.lambda$configure$1(IAMClientCallbackHandler.java:54)
	at java.base/java.util.Optional.map(Optional.java:265)
	at software.amazon.msk.auth.iam.IAMClientCallbackHandler.configure(IAMClientCallbackHandler.java:54)
	at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:128)
	... 19 more
```

Note, the application jar uploaded to Kinesis does include the class:

```
$  jar tf ./target/main-app.jar | grep DefaultAWSCredentialsProviderChain
com/amazonaws/services/kinesisanalytics/shaded/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.class
com/amazonaws/auth/DefaultAWSCredentialsProviderChain.class
```

I can even include the following in my main.kt without throwing an error:

```
import com.amazonaws.auth.DefaultAWSCredentialsProviderChain
// ...

fun main() {
    val kafkaProperties = Properties()
    kafkaProperties.setProperty("bootstrap.servers", config.propertiesBootstrapServers)
    // See https://github.com/aws/aws-msk-iam-auth#configuring-a-kafka-client-to-use-aws-iam
    kafkaProperties.setProperty("security.protocol", "SASL_SSL")
    kafkaProperties.setProperty("sasl.mechanism", "AWS_MSK_IAM")
    kafkaProperties.setProperty("sasl.jaas.config", "software.amazon.msk.auth.iam.IAMLoginModule required;")
    kafkaProperties.setProperty("sasl.client.callback.handler.class", "software.amazon.msk.auth.iam.IAMClientCallbackHandler")
    val kafkaConsumer = FlinkKafkaConsumer("topic", deserializer, kafkaProperties)
    val kafkaStream = environment.addSource(kafkaConsumer)

    // ...
}
```

POM.xml:

```
      <?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>my-app</artifactId>
    <groupId>com.example</groupId>
    <version>0.1</version>
    <packaging>jar</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.code.style>official</kotlin.code.style>
        <kotlin.compiler.jvmTarget>1.8</kotlin.compiler.jvmTarget>
    </properties>

    <repositories>
        <repository>
            <id>mavenCentral</id>
            <url>https://repo1.maven.org/maven2/</url>
        </repository>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
        </repository>
        <repository>
            <id>icm</id>
            <url>http://maven.icm.edu.pl/artifactory/repo/</url>
        </repository>
    </repositories>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>1.4.32</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <id>my-app</id>
                        <phase>package</phase>
                        <goals> <goal>single</goal> </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>src/main/assembly/app.xml</descriptor>
                            </descriptors>
                            <archive>
                                <manifest>
                                    <addClasspath>true</addClasspath>
                                    <mainClass>com.example.MainKt</mainClass>
                                </manifest>
                            </archive>
                            <finalName>main</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>6</source>
                    <target>6</target>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.amazonaws</groupId>
                <artifactId>aws-java-sdk-bom</artifactId>
                <!-- Get the latest SDK version from https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bom -->
                <version>1.11.1020</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <!-- provided -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-java_2.11</artifactId>
            <version>1.11.3</version>
            <scope>provided</scope>
        </dependency>

        <!-- compile -->
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.4.32</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test</artifactId>
            <version>1.4.32</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit5</artifactId>
            <version>1.4.32</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-kafka_2.11</artifactId>
            <version>1.11.3</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.apache.flink/flink-formats -->
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-formats</artifactId>
            <version>1.11.3</version>
            <type>pom</type>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.2.20</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-connector-jdbc_2.11</artifactId>
            <version>1.11.3</version>
        </dependency>
        <dependency>
            <groupId>com.sksamuel.hoplite</groupId>
            <artifactId>hoplite-core</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.sksamuel.hoplite</groupId>
            <artifactId>hoplite-toml</artifactId>
            <version>1.4.1</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-kinesisanalytics-runtime</artifactId>
            <version>1.2.0</version>
        </dependency>
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-kinesisanalytics-flink</artifactId>
            <version>2.0.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-logs -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk-logs</artifactId>
            <version>1.11.1020</version>
        </dependency>

        <dependency>
            <groupId>com.twitter</groupId>
            <artifactId>chill-protobuf</artifactId>
            <version>0.7.6</version>
            <!-- exclusions for dependency conversion -->
            <exclusions>
                <exclusion>
                    <groupId>com.esotericsoftware.kryo</groupId>
                    <artifactId>kryo</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- We need protobuf for chill-protobuf -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
            <version>3.17.1</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.msk</groupId>
            <artifactId>aws-msk-iam-auth</artifactId>
            <version>1.0.0</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.amazonaws.auth/aws-java-sdk -->
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.11.1020</version>
        </dependency>

        <!-- test -->
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.12.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-core</artifactId>
            <version>1.4.3</version>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-coroutines-test</artifactId>
            <version>1.4.3</version>
            <type>pom</type>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
        <!-- https://stackoverflow.com/a/63839303/1149459 -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.3</version>
            <scope>test</scope>
        </dependency>
        <!-- https://mvnrepository.com/artifact/io.confluent/kafka-protobuf-serializer -->
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-protobuf-serializer</artifactId>
            <version>5.5.1</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

</project>

```

**Comment by gokul2411s** [comment]
A few questions to help diagnosis.

1. Can you identify the version of the Kafka client used at runtime?
2. Does using a different Kafka client version fix the problem?
3. Is this issue happening deterministically?

**Comment by erichulburd** [comment]
Appreciate your response.

1. 2.8.0
2. I've not tried, but since AWS recommended version is 2.6.0 I will give that a try and follow up (this may take a couple of days).
3. Yes, it reliably recurs on separate deployments as well as separate restarts by Flink task manager.

**Comment by amitgurdasani** [comment]
Could there be a possibility that there is a class conflict between some of the transitive dependencies of the MSK Library for IAM Authentication and the AWS SDK version you are using (1.11.1020)? I suggest using

```
mvn dependency:tree
```

to see if there are any significant version conflicts. Another approach is to use the [Maven Enforcer plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/), though that approach is heavy-weight.

This NoClassDefFoundError exception can be thrown if a static initializer throws an exception while the class is being loaded. As it happens, the DefaultAWSCredentialsProviderChain [implements a static singleton](https://github.com/aws/aws-sdk-java/blob/1.11.1020/aws-java-sdk-core/src/main/java/com/amazonaws/auth/DefaultAWSCredentialsProviderChain.java). If there was an exception thrown in the constructor (say, a NoSuchMethodError due to a binary incompatibility with a transitive dependency), a NoClassDefFoundError could occur.

How are you attempting to run the Flink application? Are you setting it up as a Kinesis Data Analytics application? If that is the case, I suggest contacting [AWS Customer Support](https://aws.amazon.com/contact-us/), who can then provide you help with your application.

If you are trying to run it standalone, I suggest starting the Flink process with [the JDWP agent](https://dzone.com/articles/remote-debugging-java-applications-with-jdwp), setting a breakpoint within your IDE or debugger in the DefaultAWSCredentialsProviderChain constructor, attaching to the Flink process and seeing if that breakpoint is reached. If so, there is a possibility that the constructor is throwing an exception. Once the constructor breakpoint is reached, you could additionally set an exception breakpoint and continue execution, which should reveal the causative exception.

**Comment by erichulburd** [comment]
I've resolved this issue by adding the following to my pom.xml:


```xml
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.12.3</version>
        </dependency>
```

Ultimately the jar file we upload to flink will include this dependency. I'm building a Kotlin app, so the following resources helped:

* https://kotlinlang.org/docs/maven.html#self-contained-jar-file
* https://stackoverflow.com/questions/8726884/create-multiple-runnable-jars-with-dependencies-included-from-a-single-maven-p
* https://stackoverflow.com/questions/15798936/creating-two-executable-jars-using-maven-assembly-plugin/15799254#15799254

The error stack above is a bit opaque - I suppose that is an upstream issue with the `DefaultAWSCredentialsProviderChain` singleton though. Debugging I had to explicitly make the following call in my main class to actually get the root error:

```
        try {
            val providerChain = DefaultAWSCredentialsProviderChain.getInstance()
            providerChain.reuseLastProvider = true
            val credentials = providerChain.credentials
            println("Access Key Id")
            println(credentials.awsAccessKeyId)
        } catch (e: Exception) {
            println(e)
        }
```
