### ISSUE TITLE
Issues getting kafka-rest working in EKS with msk-iam authentication

### ISSUE THREAD

**Issue by johhil** [aws/aws-msk-iam-auth#46]
## Background
I try to set up kafka-rest in EKS using aws-msk-iam-auth when connecting to AWS msk.

For some reason I do not manage to get the SASL configuration to work. When I start the container I get the following error:
```
[main] INFO org.apache.kafka.common.security.authenticator.AbstractLogin - Successfully logged in.
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka version: 2.2.2-cp5
[main] INFO org.apache.kafka.common.utils.AppInfoParser - Kafka commitId: f1f4b0eac6ef7610
[kafka-admin-client-thread | adminclient-1] INFO org.apache.kafka.common.network.Selector - [AdminClient clientId=adminclient-1] Failed authentication with ## Removed boker URL ##  (An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.)
[kafka-admin-client-thread | adminclient-1] WARN org.apache.kafka.clients.admin.internals.AdminMetadataManager - [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error
org.apache.kafka.common.errors.SaslAuthenticationException: An error: (java.security.PrivilegedActionException: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]) occurred when evaluating SASL token received from the Kafka Broker. Kafka Client will go to AUTHENTICATION_FAILED state.
Caused by: javax.security.sasl.SaslException: Exception while evaluating challenge [Caused by javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback]
       at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:113)
       at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.lambda$createSaslToken$1(SaslClientAuthenticator.java:461)
       at java.security.AccessController.doPrivileged(Native Method)
       at javax.security.auth.Subject.doAs(Subject.java:422)
       at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.createSaslToken(SaslClientAuthenticator.java:461)
       at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendSaslClientToken(SaslClientAuthenticator.java:370)
       at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.sendInitialToken(SaslClientAuthenticator.java:290)
       at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:230)
       at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:173)
       at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
       at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
       at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:538)
       at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1131)
       at java.lang.Thread.run(Thread.java:748)
Caused by: javax.security.auth.callback.UnsupportedCallbackException: Unrecognized SASL ClientCallback
       at org.apache.kafka.common.security.authenticator.SaslClientCallbackHandler.handle(SaslClientCallbackHandler.java:98)
       at software.amazon.msk.auth.iam.internals.IAMSaslClient.generateClientMessage(IAMSaslClient.java:138)
       at software.amazon.msk.auth.iam.internals.IAMSaslClient.evaluateChallenge(IAMSaslClient.java:95)
       ... 13 more
```
I have tested both to add the jar to the classpath and adding the jar to a folder on the classpath but all with the same result. The issue is similar to https://github.com/aws/aws-msk-iam-auth/issues/11 but from the logs it looks as at least some parts of the software.amazon.msk.auth.iam class is loaded.

## Configuration used 

Using [aws-msk-iam-auth](https://github.com/aws/aws-msk-iam-auth) version 1.1.1. I have set the configuration parameters 

```
KAFKA_REST_CLIENT_SASL_MECHANISM=AWS_MSK_IAM
KAFKA_REST_CLIENT_SECURITY_PROTOCOL=SASL_SSL
KAFKA_REST_CLIENT_SASL_JAAS_CONFIG=software.amazon.msk.auth.iam.IAMLoginModule required;
KAFKA_REST_CLIENT_SASL_LOGIN_CALLBACK_HANDLER_CLASS=software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

Which generates the file /etc/kafka-rest/kafka-rest.properties at start with the following content
```
client.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
client.sasl.mechanism=AWS_MSK_IAM
bootstrap.servers=<Includes full path to my MSK port included>
client.sasl.login.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
debug=true
client.security.protocol=SASL_SSL
host.name=kafka-proxy
```

Thanks

**Comment by sayantacC** [comment]
I apologize for the delayed response.
The underlying issue seems to be that the `IAMSaslClient` is being loaded and used but not the `IAMClientCallbackHandler`. It is using the default `SaslClientCallbackHandler` which does not know how to handle the `AWSCredentialCallback`.

I think it is happening because the configuration property for the client call back handler in the Kafka java client is`sasl.client.callback.handler.class` not `sasl.login.callback.handler.class`.
So, in kafka-rest. the property will have to be 
`client.sasl.client.callback.handler.class = software.amazon.msk.auth.iam.IAMClientCallbackHandler`

Let me know, if this unblocks you. 
Sorry about the delay again.

**Comment by sayantacC** [comment]
Closing due to lack of response.

**Comment by noahhai** [comment]
I have the same issue. I tried the suggested workaround but hasn't worked.

kafka-rest.properties:

```
client.sasl.jaas.config=software.amazon.msk.auth.iam.IAMLoginModule required;
client.sasl.mechanism=AWS_MSK_IAM
bootstrap.servers=****
client.security.protocol=SASL_SSL
host.name=kafka-proxy
```
AND
```
client.sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
OR
client.sasl.login.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
OR
sasl.client.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
OR
sasl.login.callback.handler.class=software.amazon.msk.auth.iam.IAMClientCallbackHandler
```

None of those have worked.

**Configuration**
aws-msk-iam-auth version =1.1.1
confluent-kafka-rest-proxy version=5.1.2
msk version=2.6.2

**Comment by noahhai** [comment]
@sayantacC figured it out; your suggested config is correct. The issue was confluent-kafka-rest-proxy version 5.1.2 does not work. Upgrading to 7.0.1 resolves.
https://docs.confluent.io/platform/current/installation/installing_cp/zip-tar.html
