### ISSUE TITLE
Kafka Consumer stuck in high CPU after heartbeat thread receives "Too many connects" error

### ISSUE THREAD

**Issue by alitto** [aws/aws-msk-iam-auth#61]
## Context
We have a 3 node Kafka cluster in Amazon MSK (m5.large instances) with IAM authentication enabled. According to the [official docs](https://docs.aws.amazon.com/msk/latest/developerguide/limits.html), these brokers have a limit of 20 TCP connections per second by default.
We run a large number of Kafka consumers across different services, which generate about 1200 tcp connections to this cluster (~400 per broker). Whenever a rolling restart happens in our MSK cluster, some of these consumers start getting `org.apache.kafka.common.errors.SaslAuthenticationException: [70705796-1567-4960-abf0-9d50d99fb6cf]: Too many connects`. This is expected given after each broker is stopped, about 400 connections are closed and clients attempt to connect to one of the other 2 available brokers, which can cause tcp connection rate to be higher than 20/sec for some time.

A few more details:
- Version of kafka-clients: 2.8.1
- Version of spring-kafka: 2.8.3

## Issue description
Although it can take some time for these consumers to reconnect after getting these "Too many connects" error, most of them can successfully recover from these errors, but others cannot and they get stuck in an endless poll loop which produces high CPU usage (100%).

The common theme across these consumers that get stuck is this message which is logged in the corresponding hearbeat thread:
```
{
   "timestamp":1646859702501,
   "stream":"stdout",
   "logtag":"F",
   "@":"2022-03-09T13:01:40.966-08:00",
   "m":"[Consumer clientId=mygroup-1, groupId=mygroup] An authentication error occurred in the heartbeat thread",
   "l":"o.a.k.c.c.i.AbstractCoordinator",
   "t":"kafka-coordinator-heartbeat-thread \\| mygroup",
   "p":"ERROR",
   "stacktrace":"org.apache.kafka.common.errors.SaslAuthenticationException: [f42c19f2-659f-4083-8007-4ff0659f80d7]: Too many connects\n"
}
```
which seems to come from [this line](https://github.com/apache/kafka/blob/c8fbe26f3bd3a7c018e7619deba002ee454208b9/clients/src/main/java/org/apache/kafka/clients/consumer/internals/AbstractCoordinator.java#L1488) in the kafka-clients library.

The thread dump for a consumer thread that gets stuck looks like this:
```
"samplePojoMessageListener-7-C-1@13584" prio=5 tid=0x2d nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.KQueue.poll(KQueue.java:-1)
	  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:122)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:124)
	  - locked <0x4aa4> (a sun.nio.ch.KQueueSelectorImpl)
	  - locked <0x4aa5> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:146)
	  at org.apache.kafka.common.network.Selector.select(Selector.java:867)
	  at org.apache.kafka.common.network.Selector.poll(Selector.java:465)
	  at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:561)
	  at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:265)
	  at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:236)
	  at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1296)
	  at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237)
	  at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1165)
	  at jdk.internal.reflect.GeneratedMethodAccessor141.invoke(Unknown Source:-1)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	  at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	  at com.sun.proxy.$Proxy173.poll(Unknown Source:-1)
	  at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:89)
	  at brave.kafka.clients.TracingConsumer.poll(TracingConsumer.java:83)
	  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doPoll(KafkaMessageListenerContainer.java:1414)
	  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1251)
	  at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1163)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	  at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:-1)
	  at java.lang.Thread.run(Thread.java:829)
```

It seems that the HeartbeatThread in kafka-clients is not expecting the `Too many connects` error during heartbeat requests, so I wonder if this TCP rate limiting implemented by AWS is compatible with the basic assumptions made by the Kafka protocol.
We are aware that TCP connection rate can be increased by opening a support case in AWS console, but that means each cluster needs this additional manual intervention which is not very convenient when infrastructure is provisioned automatically.

## Additional info

Consumer configs:
```
allow.auto.create.topics = true
auto.commit.interval.ms = 5000
auto.offset.reset = earliest
bootstrap.servers = [b-3.XXX.c8.kafka.us-west-2.amazonaws.com:9098, b-1.XXX.c8.kafka.us-west-2.amazonaws.com:9098, b-2.XXX.c8.kafka.us-west-2.amazonaws.com:9098]
check.crcs = true
client.dns.lookup = use_all_dns_ips
client.id = consumer-samplePojoMessageListener-1
client.rack = 
connections.max.idle.ms = 540000
default.api.timeout.ms = 60000
enable.auto.commit = false
exclude.internal.topics = true
fetch.max.bytes = 52428800
fetch.max.wait.ms = 2000
fetch.min.bytes = 1
group.id =samplePojoMessageListener
group.instance.id = null
heartbeat.interval.ms = 3000
interceptor.classes = []
internal.leave.group.on.close = true
internal.throw.on.fetch.stable.offset.unsupported = false
isolation.level = read_committed
key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
max.partition.fetch.bytes = 1048576
max.poll.interval.ms = 300000
max.poll.records = 10
metadata.max.age.ms = 300000
metric.reporters = []
metrics.num.samples = 2
metrics.recording.level = INFO
metrics.sample.window.ms = 30000
partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor, class org.apache.kafka.clients.consumer.CooperativeStickyAssignor]
receive.buffer.bytes = 65536
reconnect.backoff.max.ms = 10000
reconnect.backoff.ms = 3000
request.timeout.ms = 30000
retry.backoff.ms = 1000
sasl.client.callback.handler.class = class software.amazon.msk.auth.iam.IAMClientCallbackHandler
sasl.jaas.config = [hidden]
sasl.kerberos.kinit.cmd = /usr/bin/kinit
sasl.kerberos.min.time.before.relogin = 60000
sasl.kerberos.service.name = null
sasl.kerberos.ticket.renew.jitter = 0.05
sasl.kerberos.ticket.renew.window.factor = 0.8
sasl.login.callback.handler.class = null
sasl.login.class = null
sasl.login.connect.timeout.ms = null
sasl.login.read.timeout.ms = null
sasl.login.refresh.buffer.seconds = 300
sasl.login.refresh.min.period.seconds = 60
sasl.login.refresh.window.factor = 0.8
sasl.login.refresh.window.jitter = 0.05
sasl.login.retry.backoff.max.ms = 10000
sasl.login.retry.backoff.ms = 100
sasl.mechanism = AWS_MSK_IAM
sasl.oauthbearer.clock.skew.seconds = 30
sasl.oauthbearer.expected.audience = null
sasl.oauthbearer.expected.issuer = null
sasl.oauthbearer.jwks.endpoint.refresh.ms = 3600000
sasl.oauthbearer.jwks.endpoint.retry.backoff.max.ms = 10000
sasl.oauthbearer.jwks.endpoint.retry.backoff.ms = 100
sasl.oauthbearer.jwks.endpoint.url = null
sasl.oauthbearer.scope.claim.name = scope
sasl.oauthbearer.sub.claim.name = sub
sasl.oauthbearer.token.endpoint.url = null
security.protocol = SASL_SSL
security.providers = null
send.buffer.bytes = 131072
session.timeout.ms = 45000
socket.connection.setup.timeout.max.ms = 30000
socket.connection.setup.timeout.ms = 10000
ssl.cipher.suites = null
ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
ssl.endpoint.identification.algorithm = https
ssl.engine.factory.class = null
ssl.key.password = null
ssl.keymanager.algorithm = SunX509
ssl.keystore.certificate.chain = null
ssl.keystore.key = null
ssl.keystore.location = null
ssl.keystore.password = null
ssl.keystore.type = JKS
ssl.protocol = TLSv1.3
ssl.provider = null
ssl.secure.random.implementation = null
ssl.trustmanager.algorithm = PKIX
ssl.truststore.certificates = null
ssl.truststore.location = null
ssl.truststore.password = null
ssl.truststore.type = JKS
value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
```

**Comment by sayantacC** [comment]
@alitto Thanks for providing the detailed report, particularly the scale and number of connections. We are looking into the issues around MSK brokers throwing a `Too many connects` exception and working on a solution. If it is possible for you, I would encourage you to open an AWS support ticket with the details as well.

**Comment by alitto** [comment]
@sayantacC I definitely will, just wanted to also post it here in case someone else comes across the same issue 🙂 
Thank you!

**Comment by dude0001** [comment]
See also #28. @alitto for what it is worth, we are trying to work around this issue by deploying a custom Lambda that queries the Kafka Connect API (custom implementation hosted in AWS ECS for us, not sure how to do this with MSK Connect) for failed connectors with this issue and restarting them. Not ideal for a real-time streaming solution but it is at least preventing system down and on-call situations for us at the moment.

**Comment by gokul2411s** [comment]
We have recently addressed this issue in MSK. We have also updated documentation at https://docs.aws.amazon.com/msk/latest/developerguide/limits.html#msk-provisioned-quota. If you still need help, please [create a support case](https://console.aws.amazon.com/support/home#/).
